version: "3.9"
services:
  postgres:
    image: postgres:15.1
    environment:
      POSTGRES_DB: "usersdb"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "root"
    ports:
      - "5434:5432"